# a partir da imagem debian
FROM debian
# executa comando
LABEL maintainer 'Cristian de Mellos <cristian.ms@hotmail.com>'

# manipula argumentos do build
ARG S3_BUCKET=files
# define uma variável de ambiente
ENV S3_BUCKET=${S3_BUCKET}