version: '3.3'
services:
  web:
    #image: php:7.2-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: meu-container-php7.2
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
    ports:
      - 8000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    container_name: meu-container-mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 3306:3306
